export class OtoscopiaEx {
    constructor(
        public Normal: string,
        public AlteracionCongenita: string,
        public Ausente: string,
        public caeNormal: string,
        public Colapsado: string,
        public Congenita: string,
        public Cerumen: string,
        public CerumenP: string,
        public CerumenT: string,
        public CerumenI: string,
        public CerumenIP: string,
        public CerumenIT: string,
        public Extraccion: string,
        public MembrNacaNor: string,
        public MembrNacaRoj: string,
        public MembrNacaOpc: string,
        public MembrNacaPerD: string,
        public MembrNacaRetD: string,
        public MembrNacaMonoD: string,
        public MembrNacaPerI: string,
        public MembrNacaRetI: string,
        public MembrNacaMonoI: string,
        public Otorragia: string,
        public Otorrea: string,
        public Otitis: string,
        public hallazgos: string,
        public cedula?: string,
        public Idotoscopia?: number
    ) {}
}
